---
bind_address: 0.0.0.0
cloud_controller_discovery_interval: 300
cloud_controller_ssl_verify_none: true
cloud_controller_uri: http://api.%IP%.xip.io
component_connection_retries: 2
data_file: data/data.json
log_file: admin_ui.log
log_file_page_size: 51200
log_file_sftp_keys: [ ]
log_files: [/var/vcap/sys/log/cloud_controller_ng/*.log, admin_ui.log]
mbus: nats://nats:%PASS%@%IP%:4222
monitored_components: [NATS, CloudController, DEA, HealthManager, Router, -Provisioner, ALL]
nats_discovery_interval: 30
nats_discovery_timeout: 10
port: 8070
receiver_emails: [ ]
sender_email:
  server: 10.10.10.10
  account: system@10.10.10.10
stats_file: data/stats.json
stats_refresh_schedules: [ '0 5 * * *' ]
stats_retries: 5
stats_retry_interval: 300
tasks_refresh_interval: 5000
uaa_admin_credentials:
  username: %USER%
  password: %PASS%
ui_credentials:
  username: %USER%
  password: %PASS%
ui_admin_credentials:
  username: %USER%
  password: %PASS%
varz_discovery_interval: 30